### ISSUE TITLE
Error while running example code of stage 2

### ISSUE THREAD

**Issue by LeonJung** [ROBOTIS-GIT/turtlebot3_machine_learning#10]
Hi,

stage 2 node suddenly faces termination when once the robot crashes onto the wall

![image](https://user-images.githubusercontent.com/12839888/46454431-0fb6b000-c7e1-11e8-8966-ad0e2de97f5c.png)

do you have any recommendation?

best

**Comment by kijongGil** [comment]
Hi @ LeonJung  :)
This error is that input shape is wrong. In stage 2, input shape(state_size) is set to 28. But, Your input shape is set to 364. Did you change sample of LDS to 24? Refer to following link.
http://emanual.robotis.com/docs/en/platform/turtlebot3/machine_learning/#set-parameters

Thanks,
Gilbert

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
