### ISSUE TITLE
Should parameters be changed if I use turtlebot3_waffle model for training?

### ISSUE THREAD

**Issue by Kanelankai** [ROBOTIS-GIT/turtlebot3_machine_learning#12]
Hello! 
I saw in the introduction about this package in e-manual, the default turtlebot3 model is burger. 
Should I change the value of some parameters in the python code if I use waffle?

In issue #8, you said the training could be faster with "real time factor 5".
Could you tell me where this factor is in the python code?

Thank you very much.

**Comment by kijongGil** [comment]
Hi @Kanelankai :)
There are no parameters you said in python code.
If you want to use waffle, typing follow command in terminal before `roslaunch turtlebot3_gazebo turtlebot3_stage_2.launch`
> export TURTLEBOT3_MODEL=waffle 

or refer to [this](http://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#turtlebot3-simulation-using-fake-node).

and there is real time factor in [your workspace]/turtlebot3_simulations/turtlebot3_gazebo/worlds/turtlebot3_stage_#.world

Thanks,
Gilbert.

**Comment by Kanelankai** [comment]
Thank you for your reply! @kijongGil 
I began training as you said using waffle in the environment of stage 4.
However, I found that the safe distance from the waffle to the obstacles is small. And waffle sometimes crashes into a wall slightly without reporting "Collision!!" and continuing to wander.
So I revised the value in file "environment_stage_4.py" line 62:
 min_range = 0.2
After adjusting this parameter, the robot succeeded to report "Collision!!" when it is going to brush past a wall.
But after training for about 150 times, the robot began to cycle in the central empty space and didn't head towards the goal.
Is there a parameter which defines the "weight" of head-to-goal action?
Thank you!

**Comment by Kanelankai** [comment]
Hello! @kijongGil 
I found that maybe I have misconstrue the introduction of using this package from e-manual.
Until now I just ran the training of stage 4 without finishing stage 1, 2 and 3.
I guess that the correct usage of this package is that I should run through all the four training stages one by one, loading the training result of former stage to continue training with the next stage.
That is to say, there is no parameter meaning the "weight" of the head-to-goal action.
I'm not sure whether I'm right or not.
Thank you for you help!

**Comment by kijongGil** [comment]
I'm sorry for late reply.
The reason that the robot began to cycle in the central empty space and didn't head towards the goal is gazebo is stop. Sometimes this happens, but I do not know the exact cause. If this happens, you have to finish the training and reload it. You can check it from follow command.
> rostopic echo /cmd_vel

If no publish /cmd_vel, gazebo is die.

And in this tutorial, each stage is independent. However, if you set the same weights at all stages, you can share a weight. For example. state_size is 26 at stage 1, state_size is 28 at state 4. So, the weight of stage 1 is can not load on stage 4.

The real time factor is my bad.  Change to `real_time_update_rate` in [your workspace]/turtlebot3_simulations/turtlebot3_gazebo/worlds/turtlebot3_stage_#.world.

**Comment by Kanelankai** [comment]
Hello! @kijongGil 
Thank you for your replying!
I checked the topic with "rostopic echo /cmd_vel" when turtlebot is cycling in the central area and found the topic had been published. 
So I used the training result of stage 2 to continue to train in stage 4.
At that time, turtlebot could move to a goal anywhere in the environment, although it moved like a drunk.
And now I have another question that how could I use the training result with a real turtlebot, not in the simulation?

**Comment by kijongGil** [comment]
That's sound good, @Kanelankai :)
I had not tried training yet in real. If you want to try it, you need to solve some problem.
First, remove noise of scan data. The real LDS data sometimes has noise in spite of nothing in front. As you know, when get the min_range < 0.2, episode is end. However, because of the noise, the episode ends in spite of nothing in the front. So, you have to filtering LDS data. 
If you have solved the noise, next problem is reset and goal position.  For solve these, you have to know process of this code. Then, when the turtlebot3 get a goal or collision, modify the code to not reset.

Do you have a your training video? I wonder how your turtlebot3 was learned.
Thanks!

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
