### ISSUE TITLE
Question about the setReward

### ISSUE THREAD

**Issue by alexofficial** [ROBOTIS-GIT/turtlebot3_machine_learning#13]
Hello,

I have a question about the formula used in the setReward:

In the [video](https://www.youtube.com/watch?v=807_cByUBSI&amp=&amp=&amp=&feature=youtu.be) that you have, the angle is calculated as `angle= pi/2 + action * p/8 + Φ` but in your enviroment stage is calculated as  `angle = -pi / 4 + heading + (pi / 8 * i) + pi / 2`. Why?

**Comment by kijongGil** [comment]
Hi @alexofficial :)
I'm sorry for late reply. I had a business trip last week.
Actually, the angle meaning of the video and the code seems to be a bit confusing.
The angle of the video is wrong, `angle = -pi/4 + action * pi/8 + Φ `is right.

**Comment by kijongGil** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by meh369** [comment]
> Hi @alexofficial :)
> I'm sorry for late reply. I had a business trip last week.
> Actually, the angle meaning of the video and the code seems to be a bit confusing.
> The angle of the video is wrong, `angle = -pi/4 + action * pi/8 + Φ `is right.

Is Φ, goal angle or yaw??

**Comment by Ac31415** [comment]
> > Hi @alexofficial :)
> 
> > I'm sorry for late reply. I had a business trip last week.
> 
> > Actually, the angle meaning of the video and the code seems to be a bit confusing.
> 
> > The angle of the video is wrong, `angle = -pi/4 + action * pi/8 + Φ `is right.
> 
> 
> 
> Is Φ,  Heading or yaw??

I have the same question, too!
