### ISSUE TITLE
Question: Where is the models such as wall, burger, obstacle, box of goal

### ISSUE THREAD

**Issue by hyunsooda** [ROBOTIS-GIT/turtlebot3_machine_learning#25]
Hi :)
I was about to add other goal box but I couldn't find the location.
There is no code related to models in the ```catkin_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_burger```

The source code not contains "goal" model not "goal_box". 
```
<?xml version='1.0'?>
<sdf version='1.6'>
  <model name='goal_box'>
    <pose frame=''>0 0 0 0 -0 -1.5708</pose>
    <link name='goal_box'>
      <visual name='goal_box'>
        <pose frame=''>0 0 0.0005 0 -0 0</pose>
        <geometry>
          <box>
            <size>0.5 0.5 0.001</size>
          </box>
        </geometry>
        <material>
          <script>
            <uri>file://media/materials/scripts/gazebo.material</uri>
            <name>Gazebo/Grey</name>
          </script>
          <ambient>1 0 0 1</ambient>
        </material>
      </visual>
      <pose frame=''>0 0 0 0 -0 0</pose>
    </link>
    <static>1</static>
  </model>
</sdf>
```

In the respawnGoal.py, 
```
self.modelPath = os.path.dirname(os.path.realpath(__file__))
        self.modelPath = \ self.modelPath.replace('turtlebot3_machine_learning/turtlebot3_dqn/src/turtlebot3_dqn',
                         'turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_square/goal_box/model.sdf')
```

I have checked that which object is set. there were total 4 objects(burger, sqaure, goal, ground_plane). but I am not really sure where it is.
![Screenshot from 2019-06-15 05-11-18](https://user-images.githubusercontent.com/12508269/59536258-2b588580-8f2e-11e9-8806-ae433b487893.png)

How could you set the model such as box of goal ? 
Thank you

**Comment by hyunsooda** [comment]
I have solved. 
let me know how can I solve it. 

Close.

**Comment by HamzaNAHID** [comment]
> I have solved.
> let me know a person who are curious so that I share it.
> 
> Close.

Hello! I am facing the same issue, can you please share how you solved it ?

**Comment by sharypovandrey** [comment]
@hyunsooda hi!
Could you let me know how you solved it?

**Comment by sharypovandrey** [comment]
I cloned https://github.com/ROBOTIS-GIT/turtlebot3_simulations repo to catkin_ws/src. It has all required files
