### ISSUE TITLE
Can't see laser with roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch

### ISSUE THREAD

**Issue by Sebastian5j** [ROBOTIS-GIT/turtlebot3_machine_learning#29]
i'm using waffle_pi so my turtlebot3_waffle_pi.gazebo.xacro file looks like this:

  <xacro:arg name="laser_visual"  default="true"/>
  <xacro:arg name="camera_visual" default="false"/>
  <xacro:arg name="imu_visual"    default="false"/>
![scanGazebo](https://user-images.githubusercontent.com/47197065/67028507-0ab55d80-f0d1-11e9-86e4-834a5e084b3c.png)

And my .bashrc :
export ROS_MASTER_URI=http://192.168.0.113:11311
export ROS_HOSTNAME=192.168.0.113
export TURTLEBOT3_MODEL=waffle_pi
#export TURTLEBOT3_MODEL=burger

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/laboratorio/anaconda2/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/laboratorio/anaconda2/etc/profile.d/conda.sh" ]; then
        . "/home/laboratorio/anaconda2/etc/profile.d/conda.sh"
    else
        export PATH="/home/laboratorio/anaconda2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
And this is what appends with $ roslaunch turtlebot3_gazebo turtlebot3_stage_1.launch

![ejecucionGazeboLaser](https://user-images.githubusercontent.com/47197065/67028094-616e6780-f0d0-11e9-9264-b056b7211cd0.png)

**Comment by rjshim** [comment]
@Sebastian5j 

I tested the same thing and it worked as the instruction.

![Screenshot from 2019-10-18 09-34-03](https://user-images.githubusercontent.com/38637417/67057210-8a533300-f18a-11e9-8785-bd32f72b9f26.png)
![Screenshot from 2019-10-18 09-34-31](https://user-images.githubusercontent.com/38637417/67057221-9808b880-f18a-11e9-8d54-09c4141c9f1a.png)

Would you just remove all packages and reinstall them and see if it works?
You have to reinstall tb3, tb3_simulations packages.

Regards,
Ryan

**Comment by Sebastian5j** [comment]
@rjshim  I did it:
sudo apt-get install ros-kinetic-turtlebot3
sudo apt-get install ros-kinetic-turtlebot3-simulations
Nothing happened, but im surprised because i thougth those packages were already installed

**Comment by rjshim** [comment]
@Sebastian5j 
Unfortunately, there is no way I can see what unnecessary modifications you made before, I suggest you reinstall the entire OS, ROS and TB3 packages and test it again. 
Ryan
