### ISSUE TITLE
Reward Function

### ISSUE THREAD

**Issue by RiyaPahwa** [ROBOTIS-GIT/turtlebot3_machine_learning#34]
Kindly explain the Reward Function used in this code. How is the reward calculated for angular movements?

**Comment by ROBOTIS-Will** [comment]
@RiyaPahwa 
The Reward Function in the code is calculated with multiplication of the Angular Reward Function by Distance Reward Function.
The Angular Reward Function is based on a trigonometric function to get a value between -1 to 1.
Thank you.
