### ISSUE TITLE
Issue while training turtlebot3

### ISSUE THREAD

**Issue by RiyaPahwa** [ROBOTIS-GIT/turtlebot3_machine_learning#35]
While training turtlebot3, it takes long time to run the episodes so, need to run it multiple times. How do we load the previous learning of turtlebot3 in new gazebo session? I have tried this by setting         self.load_model = True and specifying the previously run episodes to self.load_episode. After this, 900 episodes have been run till now but turtlebot3 has not reached the goal yet. The world I have been using is stage 4 after removing the moving obstacles from that. Please tell me if I am doing anything wrong.

**Comment by ROBOTIS-Will** [comment]
@RiyaPahwa 
Please refer to [this issue thread](https://github.com/ROBOTIS-GIT/turtlebot3_machine_learning/issues/7) regarding reusing saved model.
Thank you.
