### ISSUE TITLE
Ros2-turtlebot3_machine_learning-Error

### ISSUE THREAD

**Issue by arun0303** [ROBOTIS-GIT/turtlebot3_machine_learning#40]
@rjshim 

Hi Ryan Jaehyun Shim,
**Ubuntu-18.04**
**Ros2 Dashing**
Tried Running Stage 1 (No Obstacle) from the below robotis link
http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_machine_learning/
Opened a Terminal:
Tried running the below command
ros2 launch turtlebot3_dqn turtlebot3_dqn_stage1.launch.py
i getting the error attached below.

Thanks 
ARUN
![Screenshot from 2020-03-26 17-04-08](https://user-images.githubusercontent.com/41463803/77643356-380e0d80-6f85-11ea-912b-6b06f8718bc3.png)

**Comment by rjshim** [comment]
@arun0303 

Would you check if you downloaded the necessary packages and colcon build them properly? If you are not familiar with how to use ROS2 yet, you would better start with ROS2 tutorials first ([Link](https://index.ros.org/doc/ros2/)).

Ryan

**Comment by arun0303** [comment]
@rjshim 
Yes i had downloaded the necessary packages and build it as mentioned in the below link and  the build was successful.
http://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_machine_learning/

$ cd ~/robotis_ws/src/
$ git clone -b ros2 https://github.com/ROBOTIS-GIT/turtlebot3_machine_learning.git
$ cd ~/robotis_ws && colcon build --symlink-install

I am not a beginner with ros2.

**Comment by rjshim** [comment]
@arun0303 

Would you test below and let me know if it still doesn't work? 
$ ros2 launch turtlebot3_gazebo turtlebot3_dqn_stage1.launch.py
$ ros2 run turtlebot3_dqn dqn_gazebo 1
$ ros2 run turtlebot3_dqn dqn_environment
$ ros2 run turtlebot3_dqn dqn_agent 1

The emanual will be also updated soon. Thank you for the report. 

![Screenshot from 2020-03-27 08-33-17](https://user-images.githubusercontent.com/38637417/77706639-4e0fe280-7006-11ea-9436-b5d6d7e718e0.png)


Ryan
