### ISSUE TITLE
Nothing is being published on /scan topic

### ISSUE THREAD

**Issue by ishaanmht** [ROBOTIS-GIT/turtlebot3_machine_learning#41]
I have started encountering this weird issue where I am unable to start training because lidar state values are never published on /scan topic. I don't why this issue has started coming up. I will be extremely grateful if anyone could provide any help.

**Comment by ROBOTIS-Will** [comment]
@ishaanmht 
Please give us more information such as your OS / ROS version, steps we can follow to reproduce the issue.
Thank you.

**Comment by ashekim** [comment]
This issue has been closed as there weren't recent activities. 
Please feel free to reopen this thread if there's any opinion to throw.

Thanks.
