### ISSUE TITLE
'Question' How to use a saved model in 'Save_model' folder

### ISSUE THREAD

**Issue by ChangkiSung** [ROBOTIS-GIT/turtlebot3_machine_learning#8]
Hi, I just started to learn turtlebot3 machine learning.

Does anyone know how to use saved model files? (stage_1_1500.h5, stage_1_1500.json).

Can I load those files to run a launch file??

Thank you.

**Comment by kijongGil** [comment]
Hi @ChangkiSung :)
Maybe this will be help you. https://github.com/ROBOTIS-GIT/turtlebot3_machine_learning/issues/7

Thanks,
Gilbert.

**Comment by ChangkiSung** [comment]
Hi @kijongGil 

Thank you for solution. It works.

I have one more quick question about the machine learning for turtlebot3.

I would like to change a real time factor to train much faster on gazebo. Does it matter for the result??

Thanks

**Comment by ChangkiSung** [comment]
Thank you!

**Comment by kijongGil** [comment]
You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by parkjonghyun00** [comment]
How to use a saved model in 'Save_model' folder?
